// 1-Create a function that squares every digit of a number.
function sumOfSquares(number){
    let sum =0
    let c= number.toString().split('')
    for(let i=0;i<c.length;i++){
        sum=sum + (c[i]**2)
    }
return sum
}
console.log(sumOfSquares(12))


// 2-Create a function that returns the mean of all digits.
function mean(number){
    let sum =0
    let c= number.toString().split('')
    for(let i=0;i<c.length;i++){
        sum=sum + Number(c[i])
    }
return [sum, ave =sum/c.length ]
}
console.log(mean(456))

// 3-Create a function that takes an array of numbers between 1 and 10
// (excluding one number) and returns the missing number.
function findOfMissedNumber(b){
    let f = b.sort((a, b) => a-b)
    for (let i =1; i< 11 ;i++){
        if(f.indexOf(i)===-1){
            return i
        }
    }
}
 console.log(findOfMissedNumber([7,8,9,1,6,3,2,5,4]))
// 4-You are given two strings s and t.
// String t is generated by randomly shuffling string s and then adding one 
// more letter at a random position.
// Return the letter that was added to t.
let t = "gjklmn" ;
let s = "ghjklmn" ;

function q4(x,y){
    let b = x.toString().split("").sort()
    let c = y.toString().split("").sort()
for(let i=0; i<c.length ;i++){
    if(b[i]!==c[i] ){
      return c[i]  
    }
}
}
console.log(q4(t,s))

